version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "php"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      symfony:
        patterns:
          - "symfony/*"
      doctrine:
        patterns:
          - "doctrine/*"
      phpstan:
        patterns:
          - "phpstan/*"
      phpunit:
        patterns:
          - "phpunit/*"
          - "sebastian/*"
          - "phar-io/*"
          - "myclabs/deep-copy"
          - "theseer/*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    versioning-strategy: "increase"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      babel:
        patterns:
          - "@babel/*"
      cypress:
        patterns:
          - "cypress"
          - "@cypress/*"
      jest:
        patterns:
          - "babel-jest"
          - "jest"
          - "jest-*"
          - "@jest/*"

  - package-ecosystem: "npm"
    directory: "/Tests/app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    versioning-strategy: "increase"
    labels:
      - "dependencies"
      - "javascript"
      - "test-app"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      webpack-encore:
        patterns:
          - "@symfony/webpack-encore"
          - "webpack*"
          - "*-loader"
      test-app-runtime:
        patterns:
          - "core-js"
          - "jquery"
